name: "ART"

exports: "mootools-art.js"

web: "[mootools.net](http://mootools.net)"

description: "The graphics framework."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[Valerio Proietti](http://mad4milk.net) && [MooTools development team](http://mootools.net/developers)"

sources:
  - "Source/ART.js"
  - "Source/ART.Canvas.js"
  - "Source/ART.VML.js"
  - "Source/ART.Shape.js"
  - "Source/ART.Font.js"
  - "Fonts/MgOpen.Moderna.js"
  - "Fonts/MgOpen.Moderna.Bold.js"
